guitars/urls.py
from django.urls import path, re_path
from . import views

# URL mapování - seznam URL adres pro aplikaci guitars
urlpatterns = [
    path('', views.index, name='index'),
    path('guitars/', views.GuitarListView.as_view(), name='guitars'),
    path('guitars/types/<str:type_name>/', views.GuitarListView.as_view(), name='guitar-type'),
    path('guitars/<int:pk>/', views.GuitarDetailView.as_view(), name='guitar-detail'),
    path('guitar/create/', views.GuitarCreate.as_view(), name='guitar-create'),
    path('guitars/<int:pk>/update/', views.GuitarUpdate.as_view(), name='guitar-update'),
    path('guitars/<int:pk>/delete/', views.GuitarDelete.as_view(), name='guitar-delete'),
    path('clear_cache/', views.clear_cache),
]

kubaweb/urls.py
import django
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

import guitars

urlpatterns = [
    path('admin/', admin.site.urls),
    path('guitars/', include('guitars.urls')),
    path('', RedirectView.as_view(url='guitars/')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'guitars.views.error_404'
handler500 = 'guitars.views.error_500'
handler403 = 'guitars.views.error_403'
handler400 = 'guitars.views.error_400'

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]
    urlpatterns += [re_path(r'^500/$', guitars.views.error_500)]
    urlpatterns += [re_path(r'^400/$', guitars.views.error_400)]
    urlpatterns += [re_path(r'^404/$', guitars.views.error_404)]
    urlpatterns += [re_path(r'^403/$', guitars.views.error_403)]


admin.site.site_header = "DK Administrace"
admin.site.site_title = "Databáze kytar"
admin.site.index_title = "Vítejte v administrační části DK"

guitars/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from django.utils.html import format_html

""" Metoda vrací cestu k uploadovaným souborů - přílohám kytar.
    Cesta má obecnou podobu: guitar/id-kytar/attachments/nazev-souboru.
    Parametr instance odkazuje na instanci (objekt) kytar.
    Parametr filename obsahuje název uploadovaného souboru. """
def attachment_path(instance, filename):
    return "guitar/" + str(instance.guitar.id) + "/attachments/" + filename


class Type(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Type name",
                            help_text='Enter type of guitar')

    class Meta:
        # atribut ordering definuje upřednostňovaný způsob řazení - zde vzestupně podle pole/sloupce name
        ordering = ["name"]
        verbose_name = "Type"
        verbose_name_plural = "Types"

    def __str__(self):
        """ Řetězec, který se používá jako textová reprezentace objektu (například v administraci aplikace).
        V našem případě bude objekt (žánr) reprezentován výpisem obsahu pole name """
        return self.name

    def guitar_count(self, obj):
        return obj.guitar_set.count()

class Guitar(models.Model):
    # Fields
    # Znakové pole o maximální délce 200 znaků pro vložení názvu kytar
    name = models.CharField(max_length=200, verbose_name="Name")
    # Textové pole pro vložení delšího textu popisujícího děj kytar
    # Formulářový prvek může zůstat prázdný - parametry blank=True, null=True
    description = models.TextField(blank=True, null=True, verbose_name="Description")
    # Celočíselné pole pro nepovinné zadání stopáže (délky) kytar v minutách
    stringnumber = models.IntegerField(blank=True, null=True,
                                  help_text="Please enter the number of strings",
                                  verbose_name="String number")
    # Pole typu image, které umožňuje upload obrázku s plakátem kytar
    image = models.ImageField(upload_to='guitar/images/%Y/%m/%d/', blank=True, null=True, verbose_name="Image")
    # Pole pro zadání desetinného čísla vyjadřujícího hodnocení kytar v rozsahu 1.0 až 10.0
    # Výchozí hodnota je nastavena na 5.0
    # K validaci hodnot jsou použity metody z balíku/knihovny django.core.validators
    rate = models.FloatField(default=5.0,
                             validators=[MinValueValidator(1.0), MaxValueValidator(10.0)],
                             null=True,
                             help_text="Please enter an float value (range 1.0 - 10.0)",
                             verbose_name="Rate")
    # Vytvoří vztah mezi modely Film a Genre typu M:N
    type = models.ManyToManyField(Type, help_text='Select a type for this guitar')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # Metadata
    class Meta:
        # Záznamy budou řazeny primárně sestupně (znaménko mínus) podle data uvedení,
        # sekundárně vzestupně podle názvu
        ordering = ["-rate", "name"]

    # Methods
    def __str__(self):
        """Součástí textové reprezentace kytar bude jeho název, rok uvedení a hodnocení"""
        return f"{self.name}, rate: {str(self.rate)}"

    def get_absolute_url(self):
        """Metoda vrací URL stránky, na které se vypisují podrobné informace o kytar"""
        return reverse('guitar-detail', args=[str(self.id)])

    def rate_percent(self):
        return format_html("{} %", int(self.rate * 10))


""" Třída Attachment je modelem pro databázový objekt (tabulku), který bude obsahovat údaje o přílohách kytar """

class Attachment(models.Model):
    # Fields
    # Povinný titulek přílohy - text do délky 200 znaků
    name = models.CharField(max_length=200, verbose_name="Name")
    # Časový údaj o poslední aktualizaci přílohy - automaticky se ukládá aktuální čas
    last_update = models.DateTimeField(auto_now=True)
    # Pole pro upload souboru
    # Parametr upload_to zajistí uložení souboru do složky specifikované v návratové hodnotě metody attachment_path
    file = models.FileField(upload_to=attachment_path, null=True, verbose_name="File")

    # Konstanta, v níž jsou ve formě n-tic (tuples) předdefinovány různé typy příloh
    TYPE_OF_ATTACHMENT = (
        ('audio', 'Audio'),
        ('image', 'Image'),
        ('text', 'Text'),
        ('video', 'Video'),
        ('other', 'Other'),
    )

    # Pole s definovanými předvolbami pro uložení typu přílohy
    type = models.CharField(max_length=5, choices=TYPE_OF_ATTACHMENT, blank=True, default='image', help_text='Select allowed attachment type', verbose_name="Attachment type")
    # Cizí klíč, který zajišťuje propojení přílohy s daným guitarem (vztah N:1)
    # Parametr on_delete slouží k zajištění tzv. referenční integrity - v případě odstranění kytar
    # budou odstraněny i všechny jeho přílohy (models.CASCADE)
    guitar = models.ForeignKey(Guitar, on_delete=models.CASCADE)

    # Metadata
    class Meta:
        # Primární seřazeno podle poslední aktualizace souborů, sekundárně podle typu přílohy
        # ordering = ["-last_update", "type"]
        order_with_respect_to = 'guitar'

    # Methods
    def __str__(self):
        """ Textová reprezentace objektu """
        return f"{self.name}, ({self.type})"

    @property
    def filesize(self):
        x = self.file.size
        y = 512000
        if x < y * 1000:
            value = round(x/1024, 2)
            ext = ' KB'
        elif x < y * 1000**2:
            value = round(x/1024*2, 2)
            ext = ' MB'
        else:
            value = round(x/1024**3, 2)
            ext = ' GB'
        return str(value)+ext


class Review(models.Model):
    text = models.TextField(verbose_name="Text")
    edit_date = models.DateTimeField(auto_now=True)
    rate = models.IntegerField(default=5,
                             validators=[MinValueValidator(1), MaxValueValidator(10)],
                             null=True,
                             help_text="Please enter an integer value (range 1 - 10)",
                             verbose_name="Rate")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    guitar = models.ForeignKey(Guitar, on_delete=models.CASCADE)

    # Metadata
    class Meta:
        order_with_respect_to = 'guitar'

guitars/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Type, Guitar


class GuitarModelForm(ModelForm):
    def clean_runtime(self):
       data = self.cleaned_data['stringnumber']
       if data <= 0 or data > 1000:
           raise ValidationError('Neplatná délka kytar')
       return data

    def clean_rate(self):
       data = self.cleaned_data['rate']
       if data < 1 or data > 10:
           raise ValidationError('Neplatné hodnocení: musí být v rozsahu 1-10')
       return data

    class Meta:
        model = Guitar
        fields = ['name', 'description', 'image', 'image', 'stringnumber', 'rate']
        labels = {'name': 'Název kytary', 'description': 'Popis kytary'}

guitars/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.decorators.cache import never_cache
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator

from guitars.forms import GuitarModelForm
from guitars.models import Guitar, Type
#from .forms import GuitarForm


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_guitars = Guitar.objects.all().count()
    guitars = Guitar.objects.order_by('-rate')[:3]

    context = {
        'num_guitars': num_guitars,
        'guitars': guitars
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class GuitarListView(ListView):
    model = Guitar

    context_object_name = 'guitar_list'   # your own name for the list as a template variable
    template_name = 'guitar/list.html'  # Specify your own template name/location
    paginate_by = 3

    def get_queryset(self):
        if 'type_name' in self.kwargs:
            return Guitar.objects.filter(type__name=self.kwargs['type_name']).all() # Get 5 books containing the title war
        else:
            return Guitar.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['num_guitars'] = len(self.get_queryset())
        if 'type_name' in self.kwargs:
            context['view_name'] = f"Typ: {self.kwargs['type_name']}"
            context['view_head'] = f"Typ Kytary: {self.kwargs['type_name']}"
        else:
            context['view_name'] = 'Kytary'
            context['view_head'] = 'Přehled kytar'
        return context

class GuitarDetailView(DetailView):
    model = Guitar

    context_object_name = 'guitar_detail'   # your own name for the list as a template variable
    template_name = 'guitar/detail.html'  # Specify your own template name/location


class TypeListView(ListView):
    model = Type
    template_name = 'blocks/type_list.html'
    context_object_name = 'types'
    queryset = Type.objects.order_by('name').all()


class TopTenListView(ListView):
    model = Guitar
    template_name = 'blocks/top_ten.html'
    context_object_name = 'guitars'
    queryset = Guitar.objects.order_by('-rate').all()[:10]


class NewGuitarListView(ListView):
    model = Guitar
    template_name = 'blocks/new_guitars.html'
    context_object_name = 'guitars'
    paginate_by = 2


class GuitarCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Guitar
    fields = ['name', 'description', 'stringnumber', 'image', 'rate', 'type']
    initial = {'rate': '5'}
    login_url = '/accounts/login/'
    permission_required = 'guitar.add_guitar'


class GuitarUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Guitar
    template_name = 'guitars/guitar_bootstrap_form.html'
    form_class = GuitarModelForm
    login_url = '/accounts/login/'
    permission_required = 'guitars.change_guitar'


class GuitarDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Guitar
    success_url = reverse_lazy('guitars')
    login_url = '/accounts/login/'
    permission_required = 'guitars.delete_guitar'


def error_404(request, exception=None):
        return render(request, 'errors/404.html')

def error_500(request):
    return render(request, 'errors/500.html')

def error_403(request, exception=None):
    return render(request, 'errors/403.html')

def error_400(request, exception=None):
    return render(request, 'errors/400.html')

@never_cache
def clear_cache(request):
    if not request.user.is_superuser:
        raise PermissionDenied
    cache.clear()
    return HttpResponse('Cache has been cleared')

guitars/templates/guitar/detail.html
{% extends "base.html" %}
{% block name %}Detail kytar{% endblock %}
{% block css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Podrobné informace</h2>
    </div>
</div>
<div class="row mt-5 mb-3">
    <div class="col-lg-6 mb-3">
        <h2 class="display-4 mb-3">{{ guitar_detail.name }}</h2>
        <div class="bg-secondary text-light p-2 mb-3">Počet strun: {{ guitar_detail.stringnumber }} strun, Hodnocení:
            {% with ''|center:guitar_detail.rate as range %}
            {% for _ in range %}★{% endfor %}
            {% endwith %}
            <b>{{ guitar_detail.rate }}</b>
        </div>
        <div class="row">
            <div class="col-md-9">{{ guitar_detail.description }}</div>
            <div class="col-md-3">
                {% if guitar_detail.image %}
                <a href="{{ guitar_detail.image.url }}" data-toggle="lightbox" data-gallery="gallery">
                    <img src="{{ guitar_detail.image.url }}" class="img-fluid" alt="Plakát k kytar">
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    </div>
    <div class="col-lg-12 mb-3 bg-info text-white">
        <h3 class="text-center p-3">Recenze</h3>
    </div>
    <div class="col-lg-12 mb-3">
        {% for review in guitar_detail.review_set.all %}
            <h4>{% if review.author.profile.avatar %}<img src="{{ review.author.profile.avatar.url }}" alt="{{ review.author.user.prijmeni }}" class="rounded-circle" width="50">{% endif %}{{ review.author }} {{ review.edit_date }}</h4>
            <p>{{ review.text }}</p>
            <hr>
        {% endfor %}
    </div>
</div>
{% if user.is_authenticated %}
<div class="row mb-3">
    <div class="col-sm-12 text-center">
        <a href="{% url 'guitar-update' guitar_detail.pk %}" class="btn btn-primary">Upravit</a>
    {% if perms.guitars.delete_guitar %}
        <a href="{% url 'guitar-delete' guitar_detail.pk %}" class="btn btn-danger">Smazat</a>
    {% endif %}
    </div>
</div>
{% endif %}
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>
<script>
    $(document).on("click", '[data-toggle="lightbox"]', function(event) {
        event.preventDefault();
        $(this).ekkoLightbox();
    });
</script>
{% endblock %}

guitars/templates/guitar/list.html
{% extends "base.html" %}
{% load bootstrap_pagination %}
{% block name %}{{ view_name }}{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">{{ view_head }}</h2>
    </div>
</div>
<div class="row">
    {% for guitar in guitar_list %}
    <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2">
        <div class="card">
            {% if guitar.image %}
            <img class="card-img-top" src="{{ guitar.image.url }}" alt="{{ guitar.name }}">
            {% endif %}
            <div class="card-body">
                <h4 class="card-name"><a href="{% url 'guitar-detail' guitar.pk %}">{{ guitar.name }}</a></h4>
                <p class="card-text">{% for type in guitar.types.all %}<a href="{% url 'guitar-type' type.name %}" class="btn btn-light">{{ type.name }}</a> {% endfor %}</p>
            {% if user.is_authenticated %}
                <a href="{% url 'guitar-detail' guitar.pk %}" class="btn btn-primary">Podrobnosti</a>
            {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% if is_paginated %}
<div class="row mt-5">
    <div class="col-12">
    {% bootstrap_paginate page_obj range=10 %}
    </div>
</div>
{% endif %}
<div class="row mt-3">
    <div class="col-sm-12">
        <h4>Celkový počet kytar: {{ num_guitars }}</h4>
    </div>
</div>
{% if perms.guitars.can_add_guitar %}
<div class="row mb-3">
    <div class="col-sm-12 text-center">
        <a href="{% url 'guitar-create' %}" class="btn btn-success">Nová kytara</a>
    </div>
</div>
{% endif %}
{% endblock %}

guitars/templates/guitar/type.html
{% extends "base.html" %}
{% block name %}Seznam kytar{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h2>Seznam kytar: {{ view.kwargs.type_name }}</h2>
    </div>
</div>
<div class="row">
    {% for guitar in guitar_type %}
    <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2">
        <div class="card">
            {% if guitar.image %}
            <img class="card-img-top" src="{{ guitar.image.url }}" alt="{{ guitar.name }}">
            {% endif %}
            <div class="card-body">
                <h4 class="card-name"><a href="{% url 'guitar-detail' guitar.pk %}">{{ guitar.name }}</a></h4>
                <p class="card-text">{% for type in guitar.type.all %}<a href="{% url 'guitar-type' type.name %}" class="btn btn-info">{{ type.name }}</a> {% endfor %}</p>
                <a href="{% url 'guitar-detail' guitar.pk %}" class="btn btn-primary">Podrobnosti</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="row">
    <div class="col-sm-12">
        <strong>Celkový počet kytar:</strong> {{ num_guitars }}
    </div>
</div>
{% endblock %}